### ISSUE TITLE
suppress Traceback & AssertionError for plugin errors

### ISSUE THREAD

**Issue by neuromusic** [napari/napari-plugin-devtools#8]
Currently, the CLI prints the full Traceback and AssertionError when a package is incompatible with napari.

## What I get

When purposefully mis-spelling `Framework :: napari` to be `Framework :: napar`, I get the following when trying to validate the package...

```bash
(base) √ napari-hdf5-labels-io % npd --validate-package  

Traceback (most recent call last):
  File "/Users/justin.kiggins/opt/anaconda3/bin/npd", line 8, in <module>
    sys.exit(main())
  File "/Users/justin.kiggins/opt/anaconda3/lib/python3.8/site-packages/napari_plugin_devtools/__main__.py", line 25, in main
    validate_packages('dist')
  File "/Users/justin.kiggins/opt/anaconda3/lib/python3.8/site-packages/napari_plugin_devtools/validation.py", line 36, in validate_packages
    assert (
AssertionError: Classifier Framework :: napari must be specified for the plugin to be discovered
```

Displaying the Traceback here is confusing because it seems like there is an error in the CLI tool itself

## What I expected

```bash
(base) √ napari-hdf5-labels-io % npd --validate-package  
Woops! You must specify "Framework :: napari" as a classifier for napari to recognize this package as containing napari plugins, but it was not found. 

The following classifiers were found:

        'Development Status :: 4 - Beta',
        'Intended Audience :: Developers',
        'Framework :: napar',
        'Topic :: Software Development :: Testing',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Operating System :: OS Independent',
        'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',

Update your classifiers to include "Framework :: napari", then rebuild the package.

```

## A proposed solution
I would recommend the following...

1. capture AssertionErrors with try/except blocks
2. where possible provide additional guidance and context to the user, as in the example above
3. use `exit(1)` or a more appropriate exit code (is there a better one?) to exit so that CI/CD pipelines still throw an error

**Comment by neuromusic** [comment]
or (perhaps better)...

```
(base) √ napari-hdf5-labels-io % npd --validate-package  
Checking for "Framework :: napari" trove classifier in `dist/napari-hdf5-labels-io-0.2.dev2.tar.gz`
We found the following classifiers in this source distribution:
        'Development Status :: 4 - Beta',
        'Intended Audience :: Developers',
        'Framework :: napar',
        'Topic :: Software Development :: Testing',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Operating System :: OS Independent',
        'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',

Woops! "Framework :: napari" was not found. You must specify as a classifier for napari to recognize this package as containing napari plugins. Please update your classifiers to include "Framework :: napari", then rebuild the source distribution.
```
